<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.17">
  <POU Name="F_ChillerLoop_Error" Id="{ac90e556-3ac2-46f7-b5b4-d1accc224a4f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_ChillerLoop_Error : FB_ChillerLoop
VAR_INPUT
END_VAR
VAR
	fbChillerLoop : FB_ChillerLoop;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbChillerLoop(bLoopTempSW := FALSE);
F_ChillerLoop_Error := fbChillerLoop;]]></ST>
    </Implementation>
    <LineIds Name="F_ChillerLoop_Error">
      <LineId Id="12" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>