<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.14">
  <POU Name="FB_Opcpa_Test" Id="{09b0b164-c94c-4024-9b95-134904e8d427}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Opcpa_Test EXTENDS FB_TestSuite
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Opcpa_Test">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>